import { EnrolledSubject, TimetableSlot, MessDayMenu, CafeItem, NoteResource, QuickNote, TodoTask, NotionMcpConfig } from '@/types';

export const INITIAL_SUBJECTS: EnrolledSubject[] = [
  {
    id: 'sdf-1',
    code: '15B11CI111',
    name: 'Software Development Fundamentals - I',
    shortName: 'SDF-1',
    attended: 28,
    total: 32,
    credits: 4,
    faculty: 'Dr. Manish Kumar Thakur',
    roomDefault: 'LT-2',
    category: 'core',
  },
  {
    id: 'maths-1',
    code: '15B11MA111',
    name: 'Mathematics - I (Calculus & Linear Algebra)',
    shortName: 'Maths-1',
    attended: 22,
    total: 28,
    credits: 4,
    faculty: 'Prof. Alka Tripathi',
    roomDefault: 'LT-1',
    category: 'maths',
  },
  {
    id: 'physics-1',
    code: '15B11PH111',
    name: 'Physics - I (Oscillations & Modern Optics)',
    shortName: 'Physics-1',
    attended: 18,
    total: 26,
    credits: 4,
    faculty: 'Dr. Navendu Goswami',
    roomDefault: 'LT-3',
    category: 'core',
  },
  {
    id: 'beee',
    code: '15B11EC111',
    name: 'Basic Electrical & Electronics Engineering',
    shortName: 'BEEE',
    attended: 21,
    total: 25,
    credits: 3,
    faculty: 'Dr. Jitendra Mohan',
    roomDefault: 'LT-2',
    category: 'core',
  },
  {
    id: 'english',
    code: '15B11HS111',
    name: 'English & Professional Communication',
    shortName: 'English',
    attended: 15,
    total: 16,
    credits: 2,
    faculty: 'Dr. Mukta Mani',
    roomDefault: 'G-12',
    category: 'humanities',
  },
  {
    id: 'sdf-lab',
    code: '15B17CI171',
    name: 'Software Development Lab - I (C Programming)',
    shortName: 'SDF Lab',
    attended: 10,
    total: 12,
    credits: 2,
    faculty: 'Er. Pulkit Mehrotra',
    roomDefault: 'CL-04 (Abb-III)',
    category: 'lab',
  },
  {
    id: 'physics-lab',
    code: '15B17PH171',
    name: 'Physics Laboratory - I',
    shortName: 'Physics Lab',
    attended: 7,
    total: 10,
    credits: 1,
    faculty: 'Dr. Anuraj Panwar',
    roomDefault: 'TS-2 Physics Block',
    category: 'lab',
  },
];

export const TIMETABLE_DATA: TimetableSlot[] = [
  // Monday
  {
    id: 'mon-1',
    day: 'Monday',
    startTime: '09:00',
    endTime: '09:50',
    subjectCode: '15B11CI111',
    subjectName: 'SDF-1 (Control Structures & Loops)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Manish K. Thakur',
  },
  {
    id: 'mon-2',
    day: 'Monday',
    startTime: '10:00',
    endTime: '10:50',
    subjectCode: '15B11MA111',
    subjectName: 'Maths-1 (Eigenvalues & Diagonalization)',
    type: 'Lecture',
    room: 'LT-1',
    faculty: 'Prof. Alka Tripathi',
  },
  {
    id: 'mon-3',
    day: 'Monday',
    startTime: '11:00',
    endTime: '11:50',
    subjectCode: '15B11PH111',
    subjectName: 'Physics-1 (Damped Harmonic Oscillations)',
    type: 'Lecture',
    room: 'LT-3',
    faculty: 'Dr. Navendu Goswami',
  },
  {
    id: 'mon-4',
    day: 'Monday',
    startTime: '12:00',
    endTime: '12:50',
    subjectCode: '15B11HS111',
    subjectName: 'English (Technical Writing Workshop)',
    type: 'Tutorial',
    room: 'G-12',
    faculty: 'Dr. Mukta Mani',
  },
  {
    id: 'mon-break',
    day: 'Monday',
    startTime: '12:50',
    endTime: '01:50',
    subjectCode: 'MESS-LUNCH',
    subjectName: 'Lunch Break (Annapurna Mess)',
    type: 'Break',
    room: 'Mess Ground Floor',
  },
  {
    id: 'mon-5',
    day: 'Monday',
    startTime: '02:00',
    endTime: '03:50',
    subjectCode: '15B17CI171',
    subjectName: 'SDF Lab-1 (Nested Loops & 2D Arrays Assignment)',
    type: 'Lab',
    room: 'CL-04 (Computer Lab)',
    faculty: 'Er. Pulkit Mehrotra',
    batch: 'Batch B3',
  },
  {
    id: 'mon-6',
    day: 'Monday',
    startTime: '04:00',
    endTime: '04:50',
    subjectCode: '15B11MA111',
    subjectName: 'Maths-1 Tutorial Sheet 4',
    type: 'Tutorial',
    room: 'FF-6',
    faculty: 'Dr. Yogesh Gupta',
  },

  // Tuesday
  {
    id: 'tue-1',
    day: 'Tuesday',
    startTime: '09:00',
    endTime: '09:50',
    subjectCode: '15B11EC111',
    subjectName: 'BEEE (Thevenin & Norton Theorems)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Jitendra Mohan',
  },
  {
    id: 'tue-2',
    day: 'Tuesday',
    startTime: '10:00',
    endTime: '10:50',
    subjectCode: '15B11PH111',
    subjectName: 'Physics-1 (Interference in Thin Films)',
    type: 'Lecture',
    room: 'LT-3',
    faculty: 'Dr. Navendu Goswami',
  },
  {
    id: 'tue-3',
    day: 'Tuesday',
    startTime: '11:00',
    endTime: '11:50',
    subjectCode: '15B11CI111',
    subjectName: 'SDF-1 (Functions & Recursion Theory)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Manish K. Thakur',
  },
  {
    id: 'tue-break',
    day: 'Tuesday',
    startTime: '12:50',
    endTime: '01:50',
    subjectCode: 'MESS-LUNCH',
    subjectName: 'Lunch Break (Annapurna Mess)',
    type: 'Break',
    room: 'Mess Ground Floor',
  },
  {
    id: 'tue-4',
    day: 'Tuesday',
    startTime: '02:00',
    endTime: '03:50',
    subjectCode: '15B17PH171',
    subjectName: 'Physics Lab (Newton\'s Rings Experiment)',
    type: 'Lab',
    room: 'TS-2 Physics Lab',
    faculty: 'Dr. Anuraj Panwar',
  },

  // Wednesday
  {
    id: 'wed-1',
    day: 'Wednesday',
    startTime: '09:00',
    endTime: '09:50',
    subjectCode: '15B11MA111',
    subjectName: 'Maths-1 (Taylor Series & Multivariable Limits)',
    type: 'Lecture',
    room: 'LT-1',
    faculty: 'Prof. Alka Tripathi',
  },
  {
    id: 'wed-2',
    day: 'Wednesday',
    startTime: '10:00',
    endTime: '10:50',
    subjectCode: '15B11CI111',
    subjectName: 'SDF-1 (Pointers & Memory Allocation in C)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Manish K. Thakur',
  },
  {
    id: 'wed-3',
    day: 'Wednesday',
    startTime: '11:00',
    endTime: '11:50',
    subjectCode: '15B11EC111',
    subjectName: 'BEEE (AC Circuit Analysis & Resonance)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Jitendra Mohan',
  },
  {
    id: 'wed-break',
    day: 'Wednesday',
    startTime: '12:50',
    endTime: '01:50',
    subjectCode: 'MESS-LUNCH',
    subjectName: 'Lunch Break (Annapurna Mess)',
    type: 'Break',
    room: 'Mess Ground Floor',
  },
  {
    id: 'wed-4',
    day: 'Wednesday',
    startTime: '02:00',
    endTime: '02:50',
    subjectCode: '15B11CI111',
    subjectName: 'SDF-1 Tutorial (Pointers Deep Dive)',
    type: 'Tutorial',
    room: 'CL-02',
    faculty: 'Er. Pulkit Mehrotra',
  },
  {
    id: 'wed-5',
    day: 'Wednesday',
    startTime: '03:00',
    endTime: '04:50',
    subjectCode: '15B17CI171',
    subjectName: 'Competitive Programming Club / Hack Session',
    type: 'Lab',
    room: 'CL-04 (Abb-III)',
    faculty: 'Student Mentors',
  },

  // Thursday
  {
    id: 'thu-1',
    day: 'Thursday',
    startTime: '09:00',
    endTime: '09:50',
    subjectCode: '15B11PH111',
    subjectName: 'Physics-1 (Diffraction Grating & Resolving Power)',
    type: 'Lecture',
    room: 'LT-3',
    faculty: 'Dr. Navendu Goswami',
  },
  {
    id: 'thu-2',
    day: 'Thursday',
    startTime: '10:00',
    endTime: '10:50',
    subjectCode: '15B11MA111',
    subjectName: 'Maths-1 (Maxima, Minima & Lagrange Multipliers)',
    type: 'Lecture',
    room: 'LT-1',
    faculty: 'Prof. Alka Tripathi',
  },
  {
    id: 'thu-3',
    day: 'Thursday',
    startTime: '11:00',
    endTime: '11:50',
    subjectCode: '15B11HS111',
    subjectName: 'English (Corporate Etiquette & GD)',
    type: 'Lecture',
    room: 'G-12',
    faculty: 'Dr. Mukta Mani',
  },
  {
    id: 'thu-break',
    day: 'Thursday',
    startTime: '12:50',
    endTime: '01:50',
    subjectCode: 'MESS-LUNCH',
    subjectName: 'Lunch Break (Special Kadhi Chawal)',
    type: 'Break',
    room: 'Mess Ground Floor',
  },
  {
    id: 'thu-4',
    day: 'Thursday',
    startTime: '02:00',
    endTime: '03:50',
    subjectCode: '15B11EC111',
    subjectName: 'BEEE Laboratory (Op-Amp & Breadboard circuits)',
    type: 'Lab',
    room: 'Basic Electronics Lab TS-1',
    faculty: 'Dr. Jitendra Mohan',
  },

  // Friday
  {
    id: 'fri-1',
    day: 'Friday',
    startTime: '09:00',
    endTime: '09:50',
    subjectCode: '15B11CI111',
    subjectName: 'SDF-1 (Structures, Unions & File I/O)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Manish K. Thakur',
  },
  {
    id: 'fri-2',
    day: 'Friday',
    startTime: '10:00',
    endTime: '10:50',
    subjectCode: '15B11EC111',
    subjectName: 'BEEE (PN Junction Diodes & Rectifiers)',
    type: 'Lecture',
    room: 'LT-2',
    faculty: 'Dr. Jitendra Mohan',
  },
  {
    id: 'fri-3',
    day: 'Friday',
    startTime: '11:00',
    endTime: '11:50',
    subjectCode: '15B11PH111',
    subjectName: 'Physics-1 Tutorial (Optics Problem Set)',
    type: 'Tutorial',
    room: 'FF-4',
    faculty: 'Dr. Anuraj Panwar',
  },
  {
    id: 'fri-break',
    day: 'Friday',
    startTime: '12:50',
    endTime: '01:50',
    subjectCode: 'MESS-LUNCH',
    subjectName: 'Lunch Break (Annapurna Mess)',
    type: 'Break',
    room: 'Mess Ground Floor',
  },
  {
    id: 'fri-4',
    day: 'Friday',
    startTime: '02:00',
    endTime: '03:50',
    subjectCode: '15B17CI171',
    subjectName: 'SDF Lab-1 (Practical Lab Evaluation - T2 prep)',
    type: 'Lab',
    room: 'CL-04 (Abb-III)',
    faculty: 'Er. Pulkit Mehrotra',
  },
];

export const MESS_MENU: Record<string, MessDayMenu> = {
  Monday: {
    day: 'Monday',
    breakfast: ['Aloo Pyaz Paratha', 'Green Mint Chutney', 'Curd', 'Poha with Sev', 'Tea / Coffee', 'Boiled Eggs / Banana'],
    lunch: ['Rajma Masala', 'Steamed Jeera Rice', 'Aloo Baingan Fry', 'Tawa Roti / Butter Roti', 'Boondi Raita', 'Fresh Green Salad'],
    snacks: ['Samosa (2 pcs)', 'Tamarind Chutney', 'Adrak Masala Chai', 'Biscuits'],
    dinner: ['Paneer Butter Masala', 'Dal Tadka', 'Jeera Rice', 'Tawa Roti', 'Gulab Jamun (2 pcs)', 'Papad'],
    specialItem: 'Hot Gulab Jamun Night',
  },
  Tuesday: {
    day: 'Tuesday',
    breakfast: ['Idli Sambhar', 'Coconut Chutney', 'Bread Butter & Jam', 'Cornflakes with Milk', 'Tea / Coffee'],
    lunch: ['Kadhi Pakoda', 'Jeera Rice', 'Bhindi Masala Fry', 'Butter Roti', 'Cucumber Salad', 'Fryums'],
    snacks: ['Veg Chowmein / Noodles', 'Red Chilli Sauce', 'Hot Chai'],
    dinner: ['Aloo Gobhi Matar', 'Dal Makhani', 'Steamed Rice', 'Tawa Roti', 'Custard with Fruits'],
    specialItem: 'Chilled Fruit Custard',
  },
  Wednesday: {
    day: 'Wednesday',
    breakfast: ['Methi / Gobhi Paratha', 'Fresh Butter & Pickle', 'Sprouts Salad', 'Bread Toast', 'Tea / Coffee'],
    lunch: ['Chole Masala', 'Bhature / Poori', 'Jeera Rice', 'Mix Veg Dry', 'Onion Mint Salad', 'Achar'],
    snacks: ['Bread Pakoda with Green Chutney', 'Hot Masala Chai'],
    dinner: ['Matar Paneer', 'Yellow Moong Dal Fry', 'Jeera Rice', 'Roti', 'Moong Dal Halwa'],
    specialItem: 'Chole Bhature Day & Moong Dal Halwa',
  },
  Thursday: {
    day: 'Thursday',
    breakfast: ['Uttapam with Sambhar', 'Tomato Chutney', 'Boiled Sprouts', 'Tea / Filter Coffee', 'Banana'],
    lunch: ['Dum Aloo Kashmiri', 'Dal Palak', 'Steamed Rice', 'Butter Roti', 'Mix Veg Raita', 'Green Salad'],
    snacks: ['Pav Bhaji (2 pav)', 'Diced Onion & Lemon', 'Hot Chai'],
    dinner: ['Shahi Paneer', 'Panchmel Dal', 'Peas Pulao', 'Phulka Roti', 'Kheer (Rice Pudding)'],
    specialItem: 'Pav Bhaji Snacks & Shahi Paneer',
  },
  Friday: {
    day: 'Friday',
    breakfast: ['Poori with Aloo Sabzi (Nagori Style)', 'Sooji Halwa', 'Pickle', 'Hot Tea / Milk'],
    lunch: ['Black Chana Curry', 'Lauki Kofta', 'Jeera Rice', 'Tawa Roti', 'Dahi Vada', 'Salad'],
    snacks: ['French Fries / Veg Cutlet', 'Tomato Ketchup', 'Cardamom Tea'],
    dinner: ['Soyabean Chaap Masala', 'Dal Arhar Fry', 'Jeera Rice', 'Butter Naan / Roti', 'Ice Cream Cup'],
    specialItem: 'Butter Naan & Vanilla Ice Cream',
  },
  Saturday: {
    day: 'Saturday',
    breakfast: ['Masala Dosa with Sambhar', 'Coconut & Red Chutneys', 'Boiled Eggs', 'Tea / Coffee'],
    lunch: ['Pindi Chole', 'Jeera Rice', 'Aloo Shimla Mirch', 'Roti', 'Mint Buttermilk (Chaas)'],
    snacks: ['Kachori with Aloo Jhol', 'Sweet Jalebi', 'Hot Chai'],
    dinner: ['Kadhai Paneer', 'Dal Makhani', 'Veg Biryani', 'Raita', 'Rasgulla'],
    specialItem: 'Kachori Jalebi Evening',
  },
  Sunday: {
    day: 'Sunday',
    breakfast: ['Club Sandwich Grilled', 'Boiled Egg / Fresh Fruit', 'Cornflakes', 'Bournvita / Tea'],
    lunch: ['Special Hyderabadi Dum Biryani (Veg/Paneer)', 'Mirchi Ka Salan', 'Burani Raita', 'Roomali Roti', 'Gulab Jamun'],
    snacks: ['Maggi Noodles with Veggies', 'Cold Coffee / Chai'],
    dinner: ['Malai Kofta', 'Yellow Dal Tadka', 'Jeera Rice', 'Butter Roti', 'Chocolate Brownie with Vanilla'],
    specialItem: 'Sunday Special Biryani & Brownie',
  },
};

export const CAFE_ITEMS: CafeItem[] = [
  // Nescafe Kiosk
  {
    id: 'nes-1',
    name: 'Nescafe Classic Cold Coffee',
    category: 'Beverages',
    price: 45,
    location: 'Nescafe Kiosk',
    isPopular: true,
    isVeg: true,
    prepTime: '2 mins',
  },
  {
    id: 'nes-2',
    name: 'Hazelnut Frappe Cold Coffee',
    category: 'Beverages',
    price: 65,
    location: 'Nescafe Kiosk',
    isPopular: true,
    isVeg: true,
    prepTime: '3 mins',
  },
  {
    id: 'nes-3',
    name: 'Hot Cappuccino / Latte',
    category: 'Beverages',
    price: 35,
    location: 'Nescafe Kiosk',
    isPopular: false,
    isVeg: true,
    prepTime: '2 mins',
  },
  {
    id: 'nes-4',
    name: 'Nescafe Special Double Cheese Maggi',
    category: 'Maggi & Rolls',
    price: 55,
    location: 'Nescafe Kiosk',
    isPopular: true,
    isVeg: true,
    prepTime: '5 mins',
  },
  {
    id: 'nes-5',
    name: 'Peri Peri Spicy Maggi',
    category: 'Maggi & Rolls',
    price: 50,
    location: 'Nescafe Kiosk',
    isPopular: true,
    isVeg: true,
    prepTime: '5 mins',
  },

  // Annapurna Tuck Shop & Sub-station Cafe
  {
    id: 'tuck-1',
    name: 'Paneer Kathi Roll',
    category: 'Maggi & Rolls',
    price: 70,
    location: 'Annapurna Tuck Shop',
    isPopular: true,
    isVeg: true,
    prepTime: '5 mins',
  },
  {
    id: 'tuck-2',
    name: 'Aloo Patty / Cheese Patty',
    category: 'Quick Bites',
    price: 25,
    location: 'Annapurna Tuck Shop',
    isPopular: false,
    isVeg: true,
    prepTime: '1 min',
  },
  {
    id: 'tuck-3',
    name: 'Jumbo Grilled Veg Cheese Sandwich',
    category: 'Quick Bites',
    price: 60,
    location: 'Sub-station Cafe',
    isPopular: true,
    isVeg: true,
    prepTime: '7 mins',
  },
  {
    id: 'tuck-4',
    name: 'Samosa Chaat (2 pcs with Chole & Chutney)',
    category: 'Quick Bites',
    price: 40,
    location: 'Annapurna Tuck Shop',
    isPopular: true,
    isVeg: true,
    prepTime: '3 mins',
  },
  {
    id: 'tuck-5',
    name: 'Executive Mini Thali (Dal, Paneer, 3 Roti, Rice)',
    category: 'Meals & Combos',
    price: 90,
    location: 'Sub-station Cafe',
    isPopular: true,
    isVeg: true,
    prepTime: '8 mins',
  },
  {
    id: 'tuck-6',
    name: 'Chole Kulche Combo (Amritsari Style)',
    category: 'Meals & Combos',
    price: 70,
    location: 'Sub-station Cafe',
    isPopular: true,
    isVeg: true,
    prepTime: '5 mins',
  },
  {
    id: 'tuck-7',
    name: 'Red Bull Energy Drink (250ml)',
    category: 'Beverages',
    price: 125,
    location: 'Annapurna Tuck Shop',
    isPopular: false,
    isVeg: true,
  },
  {
    id: 'tuck-8',
    name: 'Fresh Lemon Ice Tea',
    category: 'Beverages',
    price: 35,
    location: 'Sub-station Cafe',
    isPopular: false,
    isVeg: true,
    prepTime: '3 mins',
  },
  {
    id: 'tuck-9',
    name: 'Choco Lava Cake / Hot Brownie',
    category: 'Bakery & Sweets',
    price: 45,
    location: 'Jaypee Night Canteen',
    isPopular: true,
    isVeg: true,
    prepTime: '2 mins',
  },
  {
    id: 'tuck-10',
    name: 'Late Night Butter Paneer Kulcha',
    category: 'Meals & Combos',
    price: 80,
    location: 'Jaypee Night Canteen',
    isPopular: true,
    isVeg: true,
    prepTime: '10 mins',
  },

  // Stationery & Tuck Shop
  {
    id: 'tuck-11',
    name: 'Lab Record Register (Hardcover 120 Pages)',
    category: 'Stationery',
    price: 60,
    location: 'Annapurna Tuck Shop',
    isPopular: true,
    isVeg: true,
  },
  {
    id: 'tuck-12',
    name: 'Assignment Sheet Pad (Ruled 50 sheets)',
    category: 'Stationery',
    price: 30,
    location: 'Annapurna Tuck Shop',
    isPopular: true,
    isVeg: true,
  },
  {
    id: 'tuck-13',
    name: 'Hauser XO / Cello Gel Pens (Blue & Black Set)',
    category: 'Stationery',
    price: 25,
    location: 'Annapurna Tuck Shop',
    isPopular: false,
    isVeg: true,
  },
  {
    id: 'tuck-14',
    name: 'Engineering Graph Sheets (Pack of 10)',
    category: 'Stationery',
    price: 20,
    location: 'Annapurna Tuck Shop',
    isPopular: false,
    isVeg: true,
  },
];

export const NOTES_RESOURCES: NoteResource[] = [
  {
    id: 'res-1',
    title: 'SDF-1 Complete C Pointers & Recursion Handout',
    subjectCode: '15B11CI111',
    subjectName: 'Software Development Fundamentals - I',
    category: 'T1 Notes',
    semester: 'Sem-1',
    format: 'PDF',
    size: '4.2 MB',
    contributor: 'Topper Notes (B3 Batch)',
    downloadsCount: 342,
  },
  {
    id: 'res-2',
    title: 'SDF-1 T1 Previous Year Question Papers (2021-2023)',
    subjectCode: '15B11CI111',
    subjectName: 'Software Development Fundamentals - I',
    category: 'PYQ',
    year: '2023',
    semester: 'Sem-1',
    format: 'PDF',
    size: '8.1 MB',
    contributor: 'JIIT Academic Hub',
    downloadsCount: 589,
  },
  {
    id: 'res-3',
    title: 'Mathematics-1 Formula Sheet (Calculus & Matrices)',
    subjectCode: '15B11MA111',
    subjectName: 'Mathematics - I',
    category: 'T1 Notes',
    semester: 'Sem-1',
    format: 'PDF',
    size: '1.8 MB',
    contributor: 'Maths Dept Scholar',
    downloadsCount: 712,
  },
  {
    id: 'res-4',
    title: 'Mathematics-1 T2 & End-Sem Solved PYQs',
    subjectCode: '15B11MA111',
    subjectName: 'Mathematics - I',
    category: 'PYQ',
    year: '2022-23',
    semester: 'Sem-1',
    format: 'PDF',
    size: '12.4 MB',
    contributor: 'JIIT Seniors Council',
    downloadsCount: 620,
  },
  {
    id: 'res-5',
    title: 'Physics-1 Optics & Thin Film Interference Derivations',
    subjectCode: '15B11PH111',
    subjectName: 'Physics - I',
    category: 'T2 Notes',
    semester: 'Sem-1',
    format: 'PDF',
    size: '5.6 MB',
    contributor: 'Physics Dept TA',
    downloadsCount: 290,
  },
  {
    id: 'res-6',
    title: 'Physics Lab Viva Voce Cheat Sheet & Readings',
    subjectCode: '15B17PH171',
    subjectName: 'Physics Laboratory - I',
    category: 'Lab Sheet',
    semester: 'Sem-1',
    format: 'PDF',
    size: '2.9 MB',
    contributor: 'Utkarsh M. (CSE)',
    downloadsCount: 440,
  },
  {
    id: 'res-7',
    title: 'BEEE Circuit Theorems, Mesh & Nodal Analysis Guide',
    subjectCode: '15B11EC111',
    subjectName: 'Basic Electrical & Electronics',
    category: 'T1 Notes',
    semester: 'Sem-1',
    format: 'PDF',
    size: '6.3 MB',
    contributor: 'ECE Society JIIT',
    downloadsCount: 388,
  },
  {
    id: 'res-8',
    title: 'English T1/T2 Reading Comprehension & Précis Writing Samples',
    subjectCode: '15B11HS111',
    subjectName: 'English & Professional Communication',
    category: 'End-Sem',
    semester: 'Sem-1',
    format: 'DOC',
    size: '1.1 MB',
    contributor: 'Humanities Dept',
    downloadsCount: 195,
  },
  {
    id: 'res-9',
    title: 'SDF Lab-1 Weekly Lab Sheets 1 to 10 (Solved Codes)',
    subjectCode: '15B17CI171',
    subjectName: 'Software Development Lab - I',
    category: 'Lab Sheet',
    semester: 'Sem-1',
    format: 'ZIP',
    size: '3.4 MB',
    contributor: 'OpenSource JIIT',
    downloadsCount: 830,
  },
];

export const INITIAL_QUICK_NOTES: QuickNote[] = [
  {
    id: 'note-1',
    title: 'SDF-1 T2 Preparation Checklist',
    content: '- Revise pointers to pointers and dynamic allocation (malloc, calloc, realloc)\n- Solve 2022 T2 question on recursion vs iteration for tree pattern\n- Check Lab Sheet 6 evaluation on Monday morning!',
    updatedAt: 'Today, 03:15 PM',
    tag: 'Academic',
  },
  {
    id: 'note-2',
    title: 'Maths-1 Tutorial 4 Doubts',
    content: '- Ask Prof. Alka Tripathi about question 7: Eigenvalues of orthogonal matrices\n- Complete Cauchy-Riemann equations homework before Wednesday 10 AM',
    updatedAt: 'Yesterday',
    tag: 'Doubts',
  },
  {
    id: 'note-3',
    title: 'Hostel & Campus Reminders',
    content: '- Annapurna mess coupon renewal at admin window\n- Gym card recharge at Sports complex\n- Library return: Thomas Calculus 14th Edition before Friday',
    updatedAt: '2 days ago',
    tag: 'Personal',
  },
];

export const INITIAL_TODOS: TodoTask[] = [
  {
    id: 'todo-1',
    title: 'Complete SDF-1 Lab Sheet 4 (Pointers & Dynamic Memory in C)',
    subjectCode: '15B17CI171',
    subjectName: 'SDF Lab - I',
    dueDate: '2026-09-29',
    priority: 'High',
    category: 'Lab records',
    completed: false,
    createdAt: '2026-09-26',
  },
  {
    id: 'todo-2',
    title: 'Solve Maths-1 Tutorial Sheet 3 (Eigenvalues & Diagonalization)',
    subjectCode: '15B11MA111',
    subjectName: 'Mathematics - I',
    dueDate: '2026-09-30',
    priority: 'High',
    category: 'Assignments',
    completed: false,
    createdAt: '2026-09-25',
  },
  {
    id: 'todo-3',
    title: 'Prepare Newton\'s Rings Experiment & Optics Viva Questions',
    subjectCode: '15B17PH171',
    subjectName: 'Physics Lab - I',
    dueDate: '2026-10-02',
    priority: 'Medium',
    category: 'T1/T2 prep',
    completed: false,
    createdAt: '2026-09-24',
  },
  {
    id: 'todo-4',
    title: 'Submit BEEE Thevenin and Norton Theorems Assignment',
    subjectCode: '15B11EC111',
    subjectName: 'BEEE',
    dueDate: '2026-10-04',
    priority: 'Medium',
    category: 'Assignments',
    completed: false,
    createdAt: '2026-09-23',
  },
  {
    id: 'todo-5',
    title: 'Review English Technical Writing & Précis Draft',
    subjectCode: '15B11HS111',
    subjectName: 'English',
    dueDate: '2026-10-05',
    priority: 'Low',
    category: 'Assignments',
    completed: false,
    createdAt: '2026-09-22',
  },
  {
    id: 'todo-6',
    title: 'Get Annapurna Mess Identity Verification Signed',
    subjectCode: 'GEN',
    subjectName: 'Campus Admin',
    dueDate: '2026-09-28',
    priority: 'Low',
    category: 'General',
    completed: true,
    createdAt: '2026-09-20',
  },
];

export const INITIAL_NOTION_MCP_CONFIG: NotionMcpConfig = {
  token: 'secret_notion_jiit_sec128_nexus_key_live_mock',
  notesDbId: 'db_8829f0a210eb47dca90c2e3',
  todosDbId: 'db_5510c4d9a29e46aab01c9d8',
  endpointUrl: 'http://localhost:3001',
  syncTodos: true,
  exportNotes: true,
  autoSyncOnChange: true,
  status: 'Connected',
  lastSyncedAt: 'Today at 03:45 PM',
  latencyMs: 42,
};

export const INITIAL_MARKS = [
  {
    id: 'm-sdf1',
    subjectCode: '24B11CS111',
    subjectName: 'Software Development Fundamentals - I',
    shortName: 'SDF-1',
    credits: 4,
    components: [
      { name: 'T1 Exam', maxMarks: 20, scoredMarks: 17.5, weight: 20, type: 'Test' },
      { name: 'T2 Exam', maxMarks: 20, scoredMarks: 16.0, weight: 20, type: 'Test' },
      { name: 'T3 Exam (Expected)', maxMarks: 35, scoredMarks: 30.0, weight: 35, type: 'EndSem' },
      { name: 'Assignment 1 (Pointers)', maxMarks: 10, scoredMarks: 9.5, weight: 10, type: 'Assignment' },
      { name: 'Assignment 2 (Recursion)', maxMarks: 10, scoredMarks: 9.0, weight: 10, type: 'Assignment' },
      { name: 'Attendance & Class Quiz', maxMarks: 5, scoredMarks: 5.0, weight: 5, type: 'Quiz' },
    ],
  },
  {
    id: 'm-maths1',
    subjectCode: '24B11MA111',
    subjectName: 'Engineering Mathematics - I',
    shortName: 'Maths-1',
    credits: 4,
    components: [
      { name: 'T1 Exam', maxMarks: 20, scoredMarks: 15.0, weight: 20, type: 'Test' },
      { name: 'T2 Exam', maxMarks: 20, scoredMarks: 14.5, weight: 20, type: 'Test' },
      { name: 'T3 Exam (Expected)', maxMarks: 35, scoredMarks: 27.0, weight: 35, type: 'EndSem' },
      { name: 'Tutorial Sheet 1-3', maxMarks: 10, scoredMarks: 8.5, weight: 10, type: 'Assignment' },
      { name: 'Mid-Sem Quiz', maxMarks: 10, scoredMarks: 8.0, weight: 10, type: 'Quiz' },
      { name: 'Class Participation', maxMarks: 5, scoredMarks: 4.5, weight: 5, type: 'Quiz' },
    ],
  },
  {
    id: 'm-phys',
    subjectCode: '24B11PH111',
    subjectName: 'Engineering Physics',
    shortName: 'Physics',
    credits: 4,
    components: [
      { name: 'T1 Exam', maxMarks: 20, scoredMarks: 13.5, weight: 20, type: 'Test' },
      { name: 'T2 Exam', maxMarks: 20, scoredMarks: 15.0, weight: 20, type: 'Test' },
      { name: 'T3 Exam (Expected)', maxMarks: 35, scoredMarks: 28.0, weight: 35, type: 'EndSem' },
      { name: 'Optics Problem Set', maxMarks: 10, scoredMarks: 9.0, weight: 10, type: 'Assignment' },
      { name: 'Surprise Test', maxMarks: 10, scoredMarks: 7.5, weight: 10, type: 'Quiz' },
      { name: 'Attendance Assessment', maxMarks: 5, scoredMarks: 4.0, weight: 5, type: 'Quiz' },
    ],
  },
  {
    id: 'm-sdflab',
    subjectCode: '24B17CS171',
    subjectName: 'SDF Lab (C Programming)',
    shortName: 'SDF Lab',
    credits: 2,
    components: [
      { name: 'Day-to-Day Lab Evaluations', maxMarks: 40, scoredMarks: 37.0, weight: 40, type: 'Assignment' },
      { name: 'Mid-Term Lab Viva', maxMarks: 20, scoredMarks: 18.0, weight: 20, type: 'Test' },
      { name: 'End-Term Lab Test (Project)', maxMarks: 40, scoredMarks: 36.0, weight: 40, type: 'EndSem' },
    ],
  },
  {
    id: 'm-workshop',
    subjectCode: '24B11ME111',
    subjectName: 'Workshop Practice & CAD',
    shortName: 'Workshop',
    credits: 2,
    components: [
      { name: 'Fitting & Carpentry Jobs', maxMarks: 40, scoredMarks: 35.0, weight: 40, type: 'Assignment' },
      { name: 'CAD Software Assignment', maxMarks: 20, scoredMarks: 19.0, weight: 20, type: 'Assignment' },
      { name: 'Viva & File Submission', maxMarks: 40, scoredMarks: 34.0, weight: 40, type: 'EndSem' },
    ],
  },
  {
    id: 'm-softskills',
    subjectCode: '24B11HS111',
    subjectName: 'Professional Communication & Soft Skills',
    shortName: 'Soft Skills',
    credits: 2,
    components: [
      { name: 'T1 Exam', maxMarks: 20, scoredMarks: 16.5, weight: 20, type: 'Test' },
      { name: 'T2 Exam', maxMarks: 20, scoredMarks: 17.0, weight: 20, type: 'Test' },
      { name: 'T3 Exam (Expected)', maxMarks: 35, scoredMarks: 31.0, weight: 35, type: 'EndSem' },
      { name: 'Group Discussion & Presentation', maxMarks: 15, scoredMarks: 14.0, weight: 15, type: 'Assignment' },
      { name: 'Resume & Business Email Draft', maxMarks: 10, scoredMarks: 9.5, weight: 10, type: 'Assignment' },
    ],
  },
];

